### ISSUE TITLE
Object.isAssignableToType: TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [runem/ts-simple-type#1]
Hi! I'm testing out using ts-simple-type in [TypeStat](https://github.com/JoshuaKGoldberg/TypeStat): https://github.com/JoshuaKGoldberg/TypeStat/pull/143/. It _mostly_ works, but for a couple of errors in that PR's [builds](https://circleci.com/gh/JoshuaKGoldberg/TypeStat/147).

Given this snippet:

```ts
try {
    if (isAssignableToType(assignedType, potentialParentType, request.services.program.getTypeChecker())) {
        return false;
    }
} catch (error) {
    debugger;
    throw error;
}
```

And these debugging statement results:

```ts
// assignedType.symbol.declarations[0].getText()
"(value?: T | PromiseLike<T>) => void"
```

```ts
> potentialParentType.symbol.declarations[0].getText()
"() => void"
```

Is this enough info to go off of?

```
Error in C:/Code/TypeStat/test/cases/unit/variables/incompleteTypes/actual.ts at node 'resolve: () => void' (position 6914):
        TypeError: Cannot read property 'type' of undefined
            at isAssignabletoSimpleTypeInternal (C:\Code\TypeStat\node_modules\ts-simple-type\lib\index.cjs.js:799:71)
            at isAssignableToSimpleType (C:\Code\TypeStat\node_modules\ts-simple-type\lib\index.cjs.js:680:12)
            at Object.isAssignableToType (C:\Code\TypeStat\node_modules\ts-simple-type\lib\index.cjs.js:906:20)
            at isAssignedTypeMissingFromDeclared (C:\Code\TypeStat\src\mutations\collecting.js:90:38)
            at ...
```

By the way, thanks for making this library! The alternative I've been using is to rewrite `tsc.js` to add `isTypeAssignableTo` as a member of type checkers. This library is a much more elegant, much higher effort solution. 💖

**Comment by runem** [comment]
Hi, thanks for considering using this library! :-) 

I cloned the branch in order to test it locally. Here are my conclusions:

First of all, I fixed the crash when comparing functions. Sorry! It's available now in version `0.2.28` of the library.

Secondly, the built in Typescript function which you used before is: 
```typescript
isTypeAssignableTo(source: Type, target: Type): boolean;
```

While the function from `ts-simple-type` is exported as:
```typescript
isAssignableToType (typeA: SimpleType, typeB: SimpleType): boolean;
```

It seems like the built in internal function checks for (source, target) while `ts-simple-type` checks (target, source). This is unnecessary confusing and I aim to align the functions with built in Typescript internal functions before version 1.0.0 of this library. Therefore I changed line 116 of `collecting.ts` to 
```typescript
if (isAssignableToType(potentialParentType, assignedType, request.services.program.getTypeChecker()))
```

This reduced the amount of errors significantly. 

The last couple of errors seems to come from `strictNullChecks`. Here's an example:

```typescript
/* ACTUAL */   let numberFilledExplicit: (number | string)[] | Array = [1];
/* EXPECTED */ let numberFilledExplicit: (number | string)[] = [1];
```

Right now i have built `ts-simple-type` with `strict: true`.

The `| Array` part comes from testing if `undefined[]` is assignable to `number[]` which is `false` when `strictNullChecks = true` and `true` when `strictNullChecks = false`. Therefore `undefined[]` is seen like it's missing from declared types (as far as I understand).

I have plans on allowing less strict comparisons as `strictNullChecks` after the library becomes even more battle tested. I will formulate and create an issue on it tomorrow 👍

**Comment by JoshuaKGoldberg** [comment]
I love ☝️this, thanks so much @runem! I'll try out `>=0.2.28` and let you know how it goes! 🙌

**Comment by runem** [comment]
No problems! I’m happy to help 🎉

**Comment by JoshuaKGoldberg** [comment]
Confirmed, https://github.com/JoshuaKGoldberg/TypeStat/pull/143/commits/c74333df49c90eef714c0f1c5e4af2dcda4a7da7 just has the `undefined[]` vs. `number[]` bug right now. Everything else is fixed.

**Comment by runem** [comment]
Great! :-) I added an issue regarding `strictNullChecks` #2 , where I will track my progress. Therefore I will close this issue for now! Thanks for opening it, and feel free to open new ones if you encounter other issues 👍
