### ISSUE TITLE
[Bug] Object with call signature not assignable to object without call signature

### ISSUE THREAD

**Issue by AnyhowStep** [runem/ts-simple-type#31]
In TS, the following is valid,

```ts
declare const src : { x : number|string, () : void };
//Assignment OK
const dst : { x : number|string } = src;
```
[Playground](http://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEYD2A7AzgF3mmZ4C54BveADwPhQFcBbAIxBgB9MYBLFAcwBp4AKAJQUAbkjbB4AXwDcAKAD08gIJo0bTihogUWAPIBpWcnRZgmCiXKFq9RiwzsuU+AF5suaUA)

`{ x : number|string, () : void }` is assignable to `{ x : number|string }`.

However, `ts-simple-type` says it is not assignable.

-----

In general, an object with call signatures is assignable to a type without call signatures.

**Comment by runem** [comment]
Thank you for creating this issue. Right now I haven't yet built functionality for parsing object literals with function signatures. However, I'll make sure to prioritize this feature.

The issue is actually a bit broader because you would bump into the same problem with construct signatures and index signatures. The following example should parse to an Object Literal type with a ConstructSignature, CallSignature, IndexSignature and a member "x". However, right now it just parses to the type "OBJECT_LITERAL" with one member: "x" of type "number|string". That's why ts-simple-type thinks that it's assignable to`{ x : number|string }`.

```typescript
interface MyInterface {
	new (): Object;
	[n: number]: string;
    () : void 
	x : number|string;
}
```

I'll track progress for supporting the above in this issue 👍
