### ISSUE TITLE
test-types-2.ts and test-types-3.ts are missing from project.

### ISSUE THREAD

**Issue by tyleo** [runem/ts-simple-type#8]
ts-simple-type/test-types/tsconfig.json contains references to two files, "test-types-2.ts" and "test-types-3.ts". However, these files are not located in the test-types directory. Are they missing, is the tsconfig.json out of date, or is there some other reason these files appear here?

**Comment by runem** [comment]
"test-types-2.ts" and "test-types-3.ts" were once in use, but not anymore, so I removed them. I just forgot to remove them from the "tsconfig.json", but I have fixed it now. Thanks again, I really appreciate your help! :tada:

**Comment by tyleo** [comment]
Thank you runem. I needed a solution for runtime type checking for a product I'm working on. I've integrated ts-simple-type and it's been great. I was hoping this repository could get to a place where I could contribute back if I discover any issues while using the package.

**Comment by runem** [comment]
That sounds really exciting, I'm happy that this library helps you! 

Thanks so much for offering your help. If you stumble upon type comparisons combinations returning unexpected results it would be really helpful to know. When I get time I'll refactor the tests and make a readme describing how to easily add new type comparison tests to the code base. Then, hopefully, it should be easier to contribute :-)

**Comment by tyleo** [comment]
No problem. I don't know how serious you are in your maintenance of ts-simple-type but I want to let you know about how I'm using it and some other issues I encountered. I don't expect any updates on these and have made changes in my own branch (https://github.com/tyleo/ts-simple-type/tree/flat-simple-type) to work around them, but nonetheless, you might be interested:

1) I'm personally using ts-simple-type on windows and, unfortunately, the built in command-line does not come with `rm`. A few of the npm scripts use `rm` to delete files so I added `rimraf` as a dev dependency in my branch and use that to delete files instead.
2) The latest versions of both npm and yarn generate lock files on install. These files should likely be checked in but if not I'd recommend adding them to .gitignore to indicate to others that they will not be checked in.
3) Another windows specific problem, I have difficulty running the command `test`. Specifically I can't set `$LINE` in any easy way. I personally just deleted the arg in my branch because I planned to run all of the tests anyways and it was an easy workaround. However, I believe there are other ways to pass args to npm scripts.
4) simple-type.ts gets significantly reformatted by prettier on my machine, no other file does. I'm not sure that master has the formatted version of this file. It may be worthwhile to run prettier on the whole codebase to make sure they are all formatted.

To describe my personal use case a little bit more:

I wanted to be able to store `SimpleType`s in a redux store. Unfortunately redux stores cannot contain self-referential objects so anything with a `SimpleTypeCircularRef` was out of the question. At first I considered flattening and unflattening the objects when they were stored or retrieved but I'm storing a lot of types so I worried about the performance of that operation. Perhaps some caching mechanism could make that work. Ultimately, I decided it would be easier and reasonably performant to delete `SimpleTypeCircularRef` and add a `SimpleTypeFlatRef` instead.

In my branch I store an index into an array which contains all of the circular types and I look up the type from the array during comparisons. Obviously this comes with other problems but it was the easiest way for me to get up and running. As you make improvements to master I plan to continue integrating them into my branch. Likewise, if I plan on making a change I will (try) to make them on the official version before integrating them into my flat-simple-type branch.

I'd love to know if you have other thoughts on a solution though. Especially if it could be added to ts-simple-type directly without damaging the API as much as my change does or if it could live side-by-side in a separate utility package.

**Comment by runem** [comment]
I'm very invested in maintaining this library, one of the reasons being that most of my other projects depend on it ([wca](https://github.com/runem/web-component-analyzer) and [lit-plugin](https://github.com/runem/ts-lit-plugin)). 

I would also love this library to come to a point where you can use it directly without having to depend on your own patched version. In fact I will soon run into the same problem as you, because I will have to serialize types to save them in json files. Also, I think that being able to handle types as JSON-serializable POJO's is a very important part of the vision of this library. Therefore I will be very open for handling circular references differently as well. I like your approach, and it would be interesting to see if `FlattedSimpleType` could be a `SimpleType` just like any other types. I opened issue #9 where we can discuss a potential solution.

Regarding your points I'm also very interested in fixing these.

1. I think this is a good solution. Of course it should be able to run on a window machine! You are very welcome to open a PR, else I will change this when I get the time.

2. I always forget this file because it has been disabled in the config on my local installation of npm (should be fixed in [this](https://github.com/runem/ts-simple-type/commit/5e7cba8d67d5b696e836827df238f8456158df49) commit)

3. I will soon be using a temporary windows computer while the keyboard of my mac is being repaired. By then I will find another way to pass arguments to npm scripts :+1: 

4. I'll run prettier on all files and look into if husky/pretty-quick has been setup correctly (should be fixed in [this](https://github.com/runem/ts-simple-type/commit/6bda9b11bd684894617331bfd9784d62b968e262) commit)
