### ISSUE TITLE
Support serializing types with circular references.

### ISSUE THREAD

**Issue by runem** [runem/ts-simple-type#9]
Right now types cannot be serialized (eg. with JSON.stringify) because of types with circular references. We should change the approach of handling circular type references so that this becomes possible.

**Comment by tyleo** [comment]
I'm glad you opened this. As I mentioned I have a solution for this in my own branch (https://github.com/tyleo/ts-simple-type/tree/flat-simple-type) but I don't think my solution is fully baked. I do think it can be helpful as the starting point for this discussion though so I'll describe what I did:

I started by deleting `SimpleCircularType` from the solution and adding:
```
export interface SimpleTypeFlatRef extends SimpleTypeBase {
    kind: SimpleTypeKind.FLAT_TYPE_REF;
    ref: number;
}
```

I believe that `SimplyTypeFlatRef` heads in the direction of a correct solution but my implementation requires additional unfortunate changes. `SimpleTypeFlatRef` has an index into an array which contains all of the circularly referenced `SimpleType`s found during calls to `toSimpleType`. Building this array is easy enough, `toSimpleTypeInternalCaching` just has to do:
```
export interface ToSimpleTypeOptions {
    circularTypesByIndex: SimpleType[]; // Added
    circularCache: WeakMap<Type, { type: SimpleType; index: number }>; // Changed
    cache: WeakMap<Type, SimpleType>;
    checker: TypeChecker;
}

...

const cachedItem = options.circularCache.get(type);
if (cachedItem !== undefined) {
    if (cachedItem.index === -1) {
        cachedItem.index = options.circularTypesByIndex.length;
        options.circularTypesByIndex.push(cachedItem.type);
    }
    return {
        kind: SimpleTypeKind.FLAT_TYPE_REF,
        ref: cachedItem.index
    };
} else { ... }
```

The problem is that `toSimpleType` can no longer return `SimpleType` only, it also has to return the cache. I wrapped these up in a new interface:
```
export interface FlattedSimpleType<T extends SimpleType = SimpleType> {
    readonly wrapped: T;
    readonly cache: SimpleType[];
}
```
Unfortunately this restricts use unless users are willing to pass `cache` around. For example, if a user "reaches in" and grabs a `SimpleType` internally stored in `FlattedSimpleType.wrapped`, they will no longer have access to the cache. So when using this API I end up with code like:
```
// Assume this has been initialized.
const flattedType: FlattedSimpleType<SimpleTypeFunction>;
const returnValue: FlattedSimpleType = {
    cache: flattedType.cache,
    wrapped: flattedType.wrapped.returnType
};
```
A naive solution would store `cache` on each `SimpleType` in the hierarchy of `SimpleType`s created by `toSimpleType` but then you may run into serialization problems again because the cache would have references all over the `SimpleType` hierarchy.

The code in the previous block could be extracted to a helper like:
```
const toFlattedType = <T extends SimpleType>(simpleType: T, flattedParent: FlattedSimpleType): FlattedSimpleType<T> => ({
    cache: flattedParent.cache,
    wrapped: simpleType,
});
```
This could be used like:
```
// Assume this has been initialized.
const flattedType: FlattedSimpleType<SimpleTypeFunction>;
const returnValue = toFlattedType(flattedType.wrapped.returnType, flattedType);
```
However, it still doesn't seem great. Perhaps an even better version would be:
```
const getFlattedType = <TParent extends SimpleType, TResult extends SimpleType>(flattedParent: FlattedSimpleType<TParent>, childGetter: (simpleType: TParent) => TResult): FlattedSimpleType<TResult> => ({
    cache: flattedParent.cache,
    wrapped: childGetter(flattedParent),
});
```
This could be used like:
```
// Assume this has been initialized.
const flattedType: FlattedSimpleType<SimpleTypeFunction>;
const returnValue = toFlattedType(flattedType, simpleType => simpleType.returnType);
```
Perhaps it's a little bit better but I still wonder whether additional improvements could be made. It would be great to come up with a solution where the existence of `FlattedSimpleType` could be eliminated entirely or made more opaque. Specifically, it is unfortunate that the extra step of carrying the cache along is necessary when working with `FlattedSimpleType` but not with regular `SimpleType`.

I'll continue to think about this and let you know if I come up with something better. But I think this is as good a starting point as any.

**Comment by tyleo** [comment]
Additionally, if a solution like this is used, I think the second code block could be improved. I haven't fully thought this out but `circularTypesByIndex` would have types it doesn't need. It would have every class, interface and object type reference rather than just ones which are used circularly. I believe this could be improved by using an additional map, array or per-type flag during calls to `toSimpleType`. But I haven't fully thought this out yet.
